### ISSUE TITLE
Mention edbg:fhelp() in wiki, and also mention feature of ModFunList

### ISSUE THREAD

**Issue by hshibuya-dd** [etnt/edbg#12]
Sure, you can assume edbg user can read erlang source, but many people don't bother that far. 

Please mention edbg:fhelp() in the documentation since it is helpful.  

Also, this bit is not mentioned in the documentation:

**ModFunList is a list of module names (atoms) or tuples {ModName, FunName}.**

it is only mentioned as:

**takes one argument containing the list of modules**

I think it is hugely userful feature and should be documented.

**Comment by etnt** [comment]
Good catch!
What do you think about: https://github.com/etnt/edbg/wiki/Tracing#edbgfhelp
Good enough?
Cheers, Tobbe

**Comment by hshibuya-dd** [comment]
Looks good.  Thanks!
